name: Deploy RAG to Server

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /srv/services/rag
                      git pull
                      docker stop rag || true
                      docker rm rag || true
                      export DOCKER_BUILDKIT=1
                      docker buildx build --platform linux/amd64 -t rag-service:1.0 --load .
                      docker network create qa-net || true
                      docker run -d --network qa-net -p 127.0.0.1:8002:8001 --name rag --env-file .env rag-service:1.0
                      docker image prune -f
